#!/usr/bin/php
<?php

/**
 * @author John Snook
 * @date May 8, 2018
 * @license https://snooky.biz/site/license
 * @copyright 2018 John Snook Consulting
 * Description of Tui
 */
use johnsnook\tui\Tui;

#use \johnsnook\tui\components\Program;

Tui::$program = new johnsnook\tui\components\Program(require __DIR__ . '/programs/' . $argv[0] . '/main.php');
$exitCode = Tui::$program->run();
exit($exitCode);

