<?php

/**
 * @author John Snook
 * @date May 23, 2018
 * @license https://snooky.biz/site/license
 * @copyright 2018 John Snook Consulting
 */

namespace johnsnook\tui\events;

/**
 * Generated by controls
 */
class ControlEvent extends \yii\base\Event {

}
